//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesWPF.Factories {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FactoryService", Namespace="http://schemas.datacontract.org/2004/07/ConsoleShoesServer.ShopService")]
    [System.SerializableAttribute()]
    public partial class FactoryService : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Factories.IShopContract")]
    public interface IShopContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopContract/getFactories", ReplyAction="http://tempuri.org/IShopContract/getFactoriesResponse")]
        ShoesWPF.Factories.FactoryService[] getFactories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopContract/getFactories", ReplyAction="http://tempuri.org/IShopContract/getFactoriesResponse")]
        System.Threading.Tasks.Task<ShoesWPF.Factories.FactoryService[]> getFactoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopContract/addFactory", ReplyAction="http://tempuri.org/IShopContract/addFactoryResponse")]
        void addFactory(ShoesWPF.Factories.FactoryService tFactory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShopContract/addFactory", ReplyAction="http://tempuri.org/IShopContract/addFactoryResponse")]
        System.Threading.Tasks.Task addFactoryAsync(ShoesWPF.Factories.FactoryService tFactory);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShopContractChannel : ShoesWPF.Factories.IShopContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShopContractClient : System.ServiceModel.ClientBase<ShoesWPF.Factories.IShopContract>, ShoesWPF.Factories.IShopContract {
        
        public ShopContractClient() {
        }
        
        public ShopContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShopContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShopContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShopContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ShoesWPF.Factories.FactoryService[] getFactories() {
            return base.Channel.getFactories();
        }
        
        public System.Threading.Tasks.Task<ShoesWPF.Factories.FactoryService[]> getFactoriesAsync() {
            return base.Channel.getFactoriesAsync();
        }
        
        public void addFactory(ShoesWPF.Factories.FactoryService tFactory) {
            base.Channel.addFactory(tFactory);
        }
        
        public System.Threading.Tasks.Task addFactoryAsync(ShoesWPF.Factories.FactoryService tFactory) {
            return base.Channel.addFactoryAsync(tFactory);
        }
    }
}
